name: simple_cluster
description: Simple clustering library implemented in Dart.
version: 0.1.0
author: Vincent Utomo <msvcode@gmail.com>
homepage: https://github.com/MSVCode/simple_cluster
repository: https://github.com/MSVCode/simple_cluster

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
dev_dependencies: